CREATE OR REPLACE VIEW public.view_journalier_travail_total
 AS
 SELECT to_char(to_date(view_covid19_ocha.date_update_ocha, 'YYYY-MM-DD')::timestamp with time zone, 'YYYY-MM-DD') AS par_jour,
    count(view_covid19_ocha.num_viro_interne) AS nbre_enreg,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_region IS NOT NULL AND (view_covid19_ocha.brute_region <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_region <> view_covid19_ocha.region) AS nbre_reg_corrige,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_region IS NOT NULL AND (view_covid19_ocha.brute_region <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_region = view_covid19_ocha.region) AS nbre_reg_correct,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_region IS NULL OR (view_covid19_ocha.brute_region = ANY (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying]))) AS nbre_reg_vide,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_district IS NOT NULL AND (view_covid19_ocha.brute_district <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_district <> view_covid19_ocha.district) AS nbre_dis_corrige,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_district IS NOT NULL AND (view_covid19_ocha.brute_district <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_district = view_covid19_ocha.district) AS nbre_dis_correct,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_district IS NULL OR (view_covid19_ocha.brute_district = ANY (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying]))) AS nbre_dis_vide,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_commune IS NOT NULL AND (view_covid19_ocha.brute_commune <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_commune <> view_covid19_ocha.commune) AS nbre_com_corrige,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_commune IS NOT NULL AND (view_covid19_ocha.brute_commune <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.brute_commune = view_covid19_ocha.commune) AS nbre_com_correct,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.brute_commune IS NULL OR (view_covid19_ocha.brute_commune = ANY (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying]))) AS nbre_com_vide,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.fsanitaire IS NOT NULL AND (view_covid19_ocha.fsanitaire <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.fsanitaire <> view_covid19_ocha.ocha_fsanitaire) AS nbre_fs_corrige,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.fsanitaire IS NOT NULL AND (view_covid19_ocha.fsanitaire <> ALL (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying])) AND view_covid19_ocha.fsanitaire = view_covid19_ocha.ocha_fsanitaire) AS nbre_fs_correct,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.fsanitaire IS NULL OR (view_covid19_ocha.fsanitaire = ANY (ARRAY['---'::character varying, '--'::character varying, '-'::character varying, 'None'::character varying, 'Manquant'::character varying, 'Manquante'::character varying, 'NA'::character varying, ''::character varying, '#NAME?'::character varying]))) AS nbre_fs_vide,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.mdg_fkt_code_fsanitaire IS NOT NULL) AS fs_dis_trouve,
    count(view_covid19_ocha.num_viro_interne) FILTER (WHERE view_covid19_ocha.mdg_fkt_code_fsanitaire IS NULL) AS fs_dis_vide
   FROM view_covid19_ocha
  GROUP BY (to_char(to_date(view_covid19_ocha.date_update_ocha, 'YYYY-MM-DD')::timestamp with time zone, 'YYYY-MM-DD'))
  ORDER BY (to_char(to_date(view_covid19_ocha.date_update_ocha, 'YYYY-MM-DD')::timestamp with time zone, 'YYYY-MM-DD'));

GRANT SELECT ON TABLE public.view_journalier_travail_total TO PG_ROLE;

